# ---- OGA numerical helpers --------------------------------------------------
#
# The Orthogonal Greedy Algorithm (OGA) that seeds the network integrators used to
# be assembled in Float64 for numerical robustness. The helpers below make it
# precision-generic (and GPU-portable) instead: the dictionary and least-squares
# fit are built in the working type `T`, and the guard rails scale with `eps(T)`
# rather than the hard-coded Float64 constants they replace.
#
# PRECISION DISCIPLINE. Everything in this file runs at the working type `T`, with
# no implicit widening: constants are materialised as `one(T)`/`zero(T)`/`T(C)`,
# reductions are written as `sum(abs2, …)` rather than `norm` (whose generic
# fallback rescales through `float`), and the dense factorisations are hand-rolled
# because LAPACK — and therefore `qr(…, ColumnNorm())` and `svd` — does not exist
# below `Float32`. The one deliberate exception is `bias_grid`/`weight_grid`, which
# generate *grid coordinates* in `Float64` and cast once; see their docstrings.

"""
    bias_grid(lo, hi, n, ::Type{T}) -> Vector{T}

Uniform grid of `n + 1` bias values from `lo` to `hi` in precision `T`.

The coordinates are generated from an integer-indexed `range` in `Float64` and then
cast to `T`, so a large `n` cannot overflow the step to zero in reduced precision: at
`Float16`, `T(n)` overflows to `Inf` for `n > 65504` and `(hi - lo)/n` evaluates to zero,
which a range built in `T` rejects with `ArgumentError: range step cannot be zero`. Only the grid
*coordinates* touch `Float64`; the seed's dictionary and solve run entirely in `T`.
"""
function bias_grid(lo, hi, n::Integer, ::Type{T}) where {T}
    return T.(range(Float64(lo), Float64(hi); length = n + 1))
end

"""
    weight_grid(lo_octave, hi_octave, n, ::Type{T}) -> Vector{T}

Logarithmically spaced grid of `n + 1` positive weight magnitudes
`2^lo_octave … 2^hi_octave` in precision `T`, for the weight axis of a 2-D `(w, b)`
dictionary.

Spacing is logarithmic because `w` sets the *length scale* of a non-homogeneous
activation (how sharply the unit transitions), and length scales are naturally
compared by ratio rather than by difference. The exponents are generated by the
same integer-indexed `Float64` range as [`bias_grid`](@ref), so a large `n` cannot
collapse the step in reduced precision, and the exponentiation is done in `Float64`
before the single cast to `T` so that an octave outside the range of `T` saturates
predictably instead of overflowing mid-computation.
"""
function weight_grid(lo_octave, hi_octave, n::Integer, ::Type{T}) where {T}
    exponents = range(Float64(lo_octave), Float64(hi_octave); length = n + 1)
    return T.(exp2.(exponents))
end

"""
    oga_norm_floor(::Type{T}, ref) -> T

Amplitude-scale floor below which a dictionary-atom norm is treated as numerically
zero (so normalization is skipped rather than dividing by noise). Scales with
`sqrt(eps(T)) * ref`, i.e. relative to the largest atom `ref` and to the working
precision: a norm smaller than this cannot be inverted reliably in `T`.

Replaces the hard-coded absolute `1e-12` guard, which sat *below* `eps(Float32)` and
so never fired in reduced precision.
"""
oga_norm_floor(::Type{T}, ref) where {T} = sqrt(eps(T)) * T(ref)

"""
    oga_tikhonov(G; C = 100) -> eltype(G)

Scale- and precision-relative Tikhonov floor `C * eps(T) * tr(G)/n` for stabilizing
a Gram / normal-equations solve `G \\ rhs` at working precision `T = eltype(G)`.
Relative to the mean diagonal `tr(G)/n`, so the effective condition-number cap tracks
the precision; `C` is a modest safety factor.

Replaces the hard-coded absolute `1e-12` / `1e-14` ridges, which round away entirely
below `eps(Float32)`. Used by [`NormalEquationsFit`](@ref) as its ridge; the default
OGA fit is [`weighted_lstsq`](@ref), which avoids forming `G` at all.
"""
function oga_tikhonov(G::AbstractMatrix{T}; C = 100) where {T}
    return T(C) * eps(T) * tr(G) / size(G, 1)
end

"""
    weighted_lstsq(Φ, w, y; C = 100) -> Vector

Solve the (ridged) quadrature-weighted least-squares fit for the output weights `x`,

    minₓ  Σⱼ wⱼ (Σᵢ xᵢ Φ[i,j] − yⱼ)²  +  λ‖x‖² ,

where each row of `Φ` is a dictionary atom sampled at the quadrature nodes, `w` are
the (positive) quadrature weights, and `y` is the fit target at those nodes.

Solved by QR on the `√w`-scaled design matrix rather than the normal equations
`Φ diag(w) Φᵀ`, so accuracy is governed by κ(Φ) instead of κ(Φ)² — the difference
that lets the fit run in reduced precision without a rank-deficient Gram matrix.

The plain QR solve is used whenever it is finite (so the Float64/Float32 atom choice
matches the Gram solution bit for bit and the greedy residual is unperturbed). Only
if it returns a non-finite result — a genuinely rank-deficient design matrix, i.e. the
Float16 case — is the fit retried with a `√λ·I` augmentation, where the ridge
`λ = C · eps(T) · tr(ÂᵀÂ)/natoms` is the precision-scaled Tikhonov floor (see
[`oga_tikhonov`](@ref)) that keeps the solution bounded and the seed finite.
"""
function weighted_lstsq(Φ::AbstractMatrix{T}, w::AbstractVector{T}, y::AbstractVector{T}; C = 100) where {T}
    sw = sqrt.(w)                     # weights are positive ⇒ real sqrt
    Â = sw .* Φ'                     # (nnodes × natoms): row j scaled by √wⱼ
    ŷ = sw .* y
    return scaled_lstsq(Â, ŷ; C = C)
end

"""
    scaled_lstsq(Â, ŷ; C = 100) -> Vector

Plain QR least squares `Â \\ ŷ` with the precision-scaled ridged retry, for an
*already* `√w`-scaled design matrix `Â` (nodes × atoms) and target `ŷ`.

This is the body of [`weighted_lstsq`](@ref) split out so that the greedy loop, which
works entirely in the `√w`-scaled space, does not re-scale on every iteration. The
ridged retry is shared by every [`OGAFit`](@ref) as a last resort, so no variant can
return a non-finite seed.
"""
function scaled_lstsq(Â::AbstractMatrix{T}, ŷ::AbstractVector{T}; C = 100) where {T}
    # `\` does not merely return garbage on a rank-deficient matrix — for a non-BLAS
    # element type it *throws*. Letting that escape would put a `SingularException` back on
    # the seed path at `Float16`, which is the exact failure this fit exists to remove.
    x = try
        Â \ ŷ                         # QR least squares
    catch e
        _is_rank_failure(e) || rethrow()
        return ridged_lstsq(Â, ŷ; C = C)
    end
    all(isfinite, x) && return x
    return ridged_lstsq(Â, ŷ; C = C)
end

function _is_rank_failure(e)
    e isa SingularException || e isa LinearAlgebra.RankDeficientException ||
        e isa LinearAlgebra.LAPACKException
end

"""
    ridged_lstsq(Â, ŷ; C = 100) -> Vector

Tikhonov-ridged least squares for the `√w`-scaled design matrix `Â`, solved as the
augmented QR problem `[Â; √λ I] x ≈ [ŷ; 0]` rather than on the normal equations, so
the ridge stabilises the solve without squaring the condition number. The ridge
`λ = C · eps(T) · tr(ÂᵀÂ)/natoms` is the precision-scaled floor of
[`oga_tikhonov`](@ref).
"""
function ridged_lstsq(Â::AbstractMatrix{T}, ŷ::AbstractVector{T}; C = 100) where {T}
    k = size(Â, 2)
    λ = T(C) * eps(T) * sum(abs2, Â) / k   # C·eps·(mean squared column norm) = tr(Gk)/k
    # The `√λ I` block is what guarantees full column rank, so a `λ` that has rounded to
    # zero (or overflowed) would leave this no more solvable than the problem it is
    # rescuing. Fall back to the bare `eps(T)` floor.
    (λ > zero(T) && isfinite(λ)) || (λ = eps(T))
    x = try
        vcat(Â, sqrt(λ) * Matrix{T}(I, k, k)) \ vcat(ŷ, zeros(T, k))
    catch e
        _is_rank_failure(e) || rethrow()
        return zeros(T, k)
    end
    all(isfinite, x) && return x
    # Last resort. A zero output weight is a poor seed but a *finite* one, and the greedy
    # loop's `fill_unused` still gives the neurons distinct `(w, b)`, so the Newton solve
    # starts from something solvable rather than from `NaN`.
    return zeros(T, k)
end

# ---- generic dense kernels --------------------------------------------------
#
# `qr(A, ColumnNorm())` and `svd(A)` are LAPACK-only: they have no generic method
# for `Float16` (nor for any non-BLAS float), which is precisely the precision the
# rank-revealing remedies exist for. Widening to `Float32` to borrow LAPACK would
# reintroduce the `Float64` island in miniature, so both are hand-rolled below.
# The selected design matrix is tiny — `nnodes × k` with `k ≤ S` (≈ 11 × 8) — so an
# unblocked textbook factorisation costs nothing measurable.

# Householder reflector for `x`, returned as `(v, β, α)` with `H = I - β v vᵀ` and
# `H x = α e₁`. `v` is unnormalised with `v[1] = 1`, the LAPACK convention, which
# avoids a division that can underflow at half precision.
function _householder(x::AbstractVector{T}) where {T}
    nx = sqrt(sum(abs2, x))
    (nx == zero(T) || !isfinite(nx)) && return (nothing, zero(T), nx)
    α = x[1] ≥ zero(T) ? -nx : nx        # away from x[1] to avoid cancellation
    v = copy(x)
    v[1] -= α
    vsq = sum(abs2, v)
    vsq == zero(T) && return (nothing, zero(T), α)
    return (v, T(2) / vsq, α)
end

"""
    pivoted_qr_lstsq(Â, ŷ, rtol) -> Vector

Rank-revealing least squares by Householder QR with column pivoting, truncated where
the pivot norm drops below `rtol` times the first (largest) pivot.

The pivoting is what makes it rank-revealing: at each step the column with the largest
remaining norm is brought forward, so a numerically dependent column is pushed to the
end and detected by its collapsed pivot rather than being solved through. Columns past
the detected rank get a zero coefficient — the returned vector always has one entry per
input column, so callers need not know the rank.

Generic in `eltype(Â)`; see the note above on why `qr(Â, ColumnNorm())` cannot be used.
"""
function pivoted_qr_lstsq(Â::AbstractMatrix{T}, ŷ::AbstractVector{T}, rtol::T) where {T}
    m, n = size(Â)
    R = Matrix{T}(Â)
    qty = Vector{T}(ŷ)
    perm = collect(1:n)
    # Squared norms of the *not yet eliminated* part of each column, recomputed rather
    # than downdated after every elimination: downdating subtracts the eliminated
    # component and loses accuracy exactly where the pivot norms collapse, which is the
    # regime this factorisation exists to detect. At `k ≤ 8` columns the recomputation is
    # free.
    cnorm = T[sum(abs2, view(R, :, j)) for j in 1:n]

    rank = 0
    pivot₁ = zero(T)
    for k in 1:min(m, n)
        p = k - 1 + argmax(view(cnorm, k:n))
        if p != k
            for r in 1:m
                R[r, k], R[r, p] = R[r, p], R[r, k]
            end
            perm[k], perm[p] = perm[p], perm[k]
            cnorm[k], cnorm[p] = cnorm[p], cnorm[k]
        end

        v, β, α = _householder(view(R, k:m, k))
        k == 1 && (pivot₁ = abs(α))
        # Rank drop: this column adds nothing the previous ones do not already span.
        (!isfinite(α) || abs(α) ≤ rtol * pivot₁) && break
        rank = k

        if v !== nothing
            for j in k:n
                col = view(R, k:m, j)
                col .-= (β * dot(v, col)) .* v
            end
            rhs = view(qty, k:m)
            rhs .-= (β * dot(v, rhs)) .* v
        end
        R[k, k] = α
        for r in (k + 1):m
            R[r, k] = zero(T)
        end

        for j in (k + 1):n
            cnorm[j] = sum(abs2, view(R, (k + 1):m, j))
        end
    end

    x = zeros(T, n)
    rank == 0 && return x
    z = UpperTriangular(view(R, 1:rank, 1:rank)) \ view(qty, 1:rank)
    for i in 1:rank
        x[perm[i]] = z[i]
    end
    return x
end

"""
    jacobi_svd(Â; sweeps = 30) -> (σ, U, V)

Singular values and factors of `Â` (nodes × atoms, tall or square) by the one-sided
Jacobi method: orthogonalise the columns pairwise by plane rotations until they are
mutually orthogonal, at which point the column norms are the singular values, the
normalised columns are `U`, and the accumulated rotations are `V`.

One-sided Jacobi is chosen over bidiagonalisation because it is short, generic in
`eltype(Â)` (LinearAlgebra's `svd` is LAPACK-only), and has *high relative accuracy*
on the small singular values — exactly the ones that decide whether the greedily
selected atoms are still independent at reduced precision. At `k ≤ 8` columns a
handful of sweeps converges and the cost is irrelevant.

`σ` is returned in the column order of `V`, not sorted.
"""
function jacobi_svd(Â::AbstractMatrix{T}; sweeps::Int = 30) where {T}
    m, n = size(Â)
    B = Matrix{T}(Â)
    V = Matrix{T}(I, n, n)

    for _ in 1:sweeps
        rotated = false
        for i in 1:(n - 1), j in (i + 1):n

            bi = view(B, :, i)
            bj = view(B, :, j)
            α = sum(abs2, bi)
            γ = sum(abs2, bj)
            β = dot(bi, bj)
            # Already orthogonal to working precision, or degenerate: nothing to do.
            (β == zero(T) || !isfinite(β)) && continue
            # `sqrt(α) * sqrt(γ)`, never `sqrt(α * γ)`: the product of two squared column
            # norms overflows `Float16` as soon as the norms exceed ~16, at which point the
            # threshold becomes `Inf`, every pair tests as "already orthogonal", and the
            # iteration silently returns the unrotated matrix — wrong singular values with
            # no error raised.
            abs(β) ≤ eps(T) * sqrt(α) * sqrt(γ) && continue
            rotated = true

            ζ = (γ - α) / (T(2) * β)
            t = (ζ ≥ zero(T) ? one(T) : -one(T)) / (abs(ζ) + sqrt(one(T) + ζ * ζ))
            c = one(T) / sqrt(one(T) + t * t)
            s = c * t

            for r in 1:m
                x, y = B[r, i], B[r, j]
                B[r, i] = c * x - s * y
                B[r, j] = s * x + c * y
            end
            for r in 1:n
                x, y = V[r, i], V[r, j]
                V[r, i] = c * x - s * y
                V[r, j] = s * x + c * y
            end
        end
        rotated || break
    end

    σ = T[sqrt(sum(abs2, view(B, :, j))) for j in 1:n]
    for j in 1:n
        if σ[j] > zero(T) && isfinite(σ[j])
            view(B, :, j) ./= σ[j]
        else
            view(B, :, j) .= zero(T)
        end
    end
    return (σ, B, V)
end

"""
    IncrementalQRState{T}(nnodes, maxcols)

Thin QR factorisation of the greedily selected design matrix, maintained by appending
one column at a time.

OGA adds exactly one atom per iteration, so re-solving a `k × k` system from scratch at
every step repeats work the previous step already did. Maintaining `Q` (orthonormal
columns) and `R` (upper triangular) instead
costs `O(k · nnodes)` per step, never forms a Gram matrix, and, as a side effect, yields
two quantities the greedy loop wants anyway:

  * the norm of the new column *after* deflation against the already-selected ones,
    which is the rank-gain the atom actually contributes (see
    [`OrthogonalProjection`](@ref)); and
  * `Q` itself, which turns the orthogonal-greedy selection score into one matrix
    product against the dictionary.

Columns are stored `√w`-scaled, so the Euclidean inner products here *are* the
quadrature-weighted ones and no re-scaling happens inside the loop.
"""
mutable struct IncrementalQRState{T}
    Q::Matrix{T}
    R::Matrix{T}
    k::Int

    function IncrementalQRState{T}(nnodes::Integer, maxcols::Integer) where {T}
        new{T}(zeros(T, nnodes, maxcols), zeros(T, maxcols, maxcols), 0)
    end
end

"""
    oga_qr_reset!(qr)

Drop all columns, reusing the storage. Called once per dimension `d` of the fit.
"""
function oga_qr_reset!(qr::IncrementalQRState{T}) where {T}
    qr.Q .= zero(T)
    qr.R .= zero(T)
    qr.k = 0
    return qr
end

"""
    oga_qr_append!(qr, a; min_gain) -> ρ

Append column `a` to the factorisation and return the deflated norm `ρ = ‖a⊥‖`, the
part of `a` orthogonal to the columns already present. The column is rejected (nothing
is appended, `ρ` still returned) when `ρ ≤ min_gain · ‖a‖`, i.e. when `a` lies in the
existing span to within the requested tolerance — the rank drop that otherwise surfaces
downstream as `SingularException: zero pivot found at index 3`.

Orthogonalisation is modified Gram–Schmidt with one reorthogonalisation pass. That
second pass is not optional bookkeeping: plain MGS loses orthogonality in proportion to
the condition number, which at `Float16` is the whole problem, whereas
reorthogonalising once restores it to `O(eps(T))` for any conditioning that has not
already collapsed.
"""
function oga_qr_append!(qr::IncrementalQRState{T}, a::AbstractVector{T}; min_gain::T = zero(T)) where {T}
    k = qr.k
    anorm = sqrt(sum(abs2, a))
    u = Vector{T}(a)
    r = zeros(T, k)

    if k > 0
        Qk = view(qr.Q, :, 1:k)
        for _ in 1:2                       # MGS + one reorthogonalisation
            c = Qk' * u
            u .-= Qk * c
            r .+= c
        end
    end

    ρ = sqrt(sum(abs2, u))
    (!isfinite(ρ) || ρ ≤ min_gain * anorm) && return ρ

    qr.k = k + 1
    qr.Q[:, qr.k] .= u ./ ρ
    for i in 1:k
        qr.R[i, qr.k] = r[i]
    end
    qr.R[qr.k, qr.k] = ρ
    return ρ
end

"""
    oga_qr_solve(qr, ŷ) -> Vector

Least-squares coefficients from the maintained factorisation: one triangular solve
`R z = Qᵀ ŷ`. Falls back to [`ridged_lstsq`](@ref) on the reconstructed design matrix
if the triangular solve is not finite, so this can never return a non-finite seed.
"""
function oga_qr_solve(qr::IncrementalQRState{T}, ŷ::AbstractVector{T}) where {T}
    k = qr.k
    k == 0 && return zeros(T, 0)
    Qk = view(qr.Q, :, 1:k)
    Rk = view(qr.R, 1:k, 1:k)
    z = UpperTriangular(Rk) \ (Qk' * ŷ)
    all(isfinite, z) && return z
    return ridged_lstsq(Qk * Rk, ŷ)
end

"""
    truncated_svd_lstsq(Â, ŷ, rtol) -> Vector

Minimum-norm least squares via the truncated pseudo-inverse: singular directions with
`σ < rtol · σ_max` are dropped instead of divided by, so a rank-deficient selected set
yields a bounded solution rather than amplified rounding noise. The most robust of the
fits, and the one to reach for when a variant must never fail at any precision.

Uses [`jacobi_svd`](@ref), so it is generic in `eltype(Â)`.
"""
function truncated_svd_lstsq(Â::AbstractMatrix{T}, ŷ::AbstractVector{T}, rtol::T) where {T}
    σ, U, V = jacobi_svd(Â)
    σmax = maximum(σ)
    x = zeros(T, size(Â, 2))
    (σmax == zero(T) || !isfinite(σmax)) && return x
    cut = rtol * σmax
    for j in eachindex(σ)
        σ[j] > cut || continue
        x .+= (dot(view(U, :, j), ŷ) / σ[j]) .* view(V, :, j)
    end
    return x
end
