# name: Documentation

# on:
#   # push:
#   #   branches:
#   #     - zeyuan

# jobs:
#   docs:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v6

#       - name: Setup Julia
#         uses: julia-actions/setup-julia@v3

#       - name: Install docs dependencies
#         run: julia --project=docs -e 'using Pkg;Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate();Pkg.build();Pkg.precompile()'

#       - name: Build docs
#         run: julia --project=docs docs/make.jl

